services:
  mahamatra:
    build:
      context: .
      dockerfile: ./docker/Dockerfile
    restart: always
    environment:
      BOT_TOKEN: "token" # Modify this
    volumes:
      - ./mahamatra.json:/bot/mahamatra.json
